name: Deploy Micro UI (Angular Web Components)

on:
  push:
    branches: [main]
    paths:
      - "micro-ui/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd micro-ui
          npm install

      - name: Build Angular Web Components
        run: |
          cd micro-ui
          npm run build -- --base-href=/micro-ui/

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./micro-ui/dist/micro-ui

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
